# Generated by Django 4.1.3 on 2022-12-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useranswer_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('quiz_index',)},
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'quiz_index')},
        ),
    ]
