# Generated by Django 4.1.3 on 2022-12-04 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_question_options_question_quiz_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
